project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - chapter_1.qmd
   
website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      # - testing.qmd
      - href: chapter_1.qmd
        text: Property prices
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
execute:
  freeze: auto

