---
title: "Words ending in -th"
editor: visual
---

Among the *many* curiosities of English is the survival of a "-th" affix, pronounced **/𝜃/**. There are two main groups of these. The first is for ordinal numbers, and there's as many of these as there are numbers, as in the fourth, the fifth and the sixth of something, the tenth, eleventh, twelfth, the hundredth, thousandth, millionth, billionth, squillionth. And of course the nth number, the umpteenth example and last but not necessarily least, the zeroth case. This affix is productive so if someone thinks up a new number – such as *i* – then we can have the *i*-th case. No doubt someone has ound reason to talk of the *minus-fourth* caseor even the *minus-oneth.*

Howandever, the focus here will be on the other group of *-th* words, a bunch of survivors from Old English, before the Sasanaigh sold out to the ruling French and the ecclesiastial Latins and the unputdownable Greeks. The -th suffix often shows up in abstract nouns used for measurement. What is the volume of a cube? The length by the breadth by the width. Or is it the length by the depth by the height? Yet there are several more. *Health, wealth, strength, warmth, growth, sloth, month, truth, filth, worth, dearth* and even *birth* and *death*.

These abstract nouns mostly derive from an adjective which, nowadays, may be rather different, in either its spelling, sound or both. My goal here is to unveil these curious patterns, although some cases may require a little background.

This lot are closely related:

-   Depth comes from Deep

-   health comes from heal

-   wealth comes from *weal* (well)

-   dearth comes from dear

In Middle English, vowels could be long or short, and the short form would be triggered when multiple consonants followed. Thus *deep* had a long \[e:\] sound but *depth* had a short \[e\]. Almost the same as *dape – depth, dape – depth*. Same vowel quality but different length. During the Great Vowel Shift, long vowels changed their quality, so that \[a:\] became \[e:\], \[e:\] became \[i:\] and \[i:\] diphthongized to \[aI\]. This is why non-English-speaking Europeans frequently confuse A with E and E with I.

One reflex of this in modern spelling is that we distinguish \<ee\> from \<e\> in some contexts, but not all, as in *serene, serenity* or the unrelated *Venus*, *venture*.

Length variation still occurs in modern English although it occurs below most people's level of perception. My name is 'Des' with a long vowel, but my full name 'Desmond' is short. Des. Desmond, Des, Desmond. The longer vowel only occurs before voiced consonants, or no consonant. Thus *Des*, which has a /z/ sound, is longer than *Jess* which has /s/*.* This distinction vanishes when there are more syllables, hence the short vowel of *Desmond* and *Dessie*.

-   Adding \[𝜃\] triggered the short version.

Back to -th words and we see a vowel variation in the following cases:

-   wide - width

-   five - fifth

-   Moon - month

The alternation does *not* occur when the base adjective ends in a vowel sound, as in

-   grow - growth

-   true - truth or in the historical pronunciation of

-   slow - sloth.

This is because you needed two consonants in a cluster to trigger the shortening of a vowel. Yet if the base form had two consonants, then it couldn't lengthen, as in

-   warm - warmth

And perhaps:

-   merry - mirth

Other examples show an unrelated process called vowel mutation, which is a topic for another day.

-   Long – length

-   Strong – strength

-   Broad – breadth

-   foul – filth

-   bear – birth

-   die – death

Finally, you may be wondering what of the words *first*, *second* and *third* cases. Are these just bastardized cases of *-th*, as they all end in a dental stop. Alas, no. *first* contains a form of the *-est* suffix for superlatives. Second comes from Latin *secundus*, although the Englishword used to be *other*, surviving in the (mostly American) phrase, *every other day.* As for *third*, I'm not sure, but my guess is that it is related. The OE form was *thridda* and may have been formed in continental Germanic before the *-th* suffix became distinct to the Insular Anglo-Saxon in Britain.

------------------------------------------------------------------------
